"""Build every image the build needs, from Smekkleysa's own catalogue.

Emits into the SAME paths the engine already expects, so app.js never has to change:

    public/img/artists/<slug>.webp     the roll plates   (one sleeve per artist)
    public/img/artists/<slug>-m.webp   the phone plate
    public/img/artists/<slug>-w.webp   the 40px wash behind an archive plate
    public/img/shop/<slug>.webp        the rail sleeves  (with prices)

Two honesty rules carried from the two previous builds on this engine:

  1. A picture is never emitted larger than its own source, and the tier a record lands
     in is decided HERE from its true pixels, not asserted in CSS.
  2. Caption, price, link and file all come out of the SAME record, so a title can never
     drift onto the wrong sleeve.

Where this catalogue differs from 12 Tónar's: 110 of the 150 fetched sleeves are
>=1440px. 12 Tónar had 29 of 345 over 1000px and the whole design had to be built around
showing covers as small objects. Here the roll can be full-bleed the way Alda's was, so
the archive-plate tier exists only as the fallback it was meant to be.
"""
import json, os, shutil, unicodedata
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_ROLL = os.path.join(ROOT, 'public/img/artists')
OUT_SHOP = os.path.join(ROOT, 'public/img/shop')

FULLBLEED = 1440        # at or above this a square sleeve may cover a 1440 viewport
ROLL_COUNT = 60
SHOP_MAX = 760          # the rail's own render size
SHOP_COUNT = 18

IS_ORDER = 'aábcdðeéfghiíjklmnoópqrstuúvwxyýzþæö'
RANK = {c: i for i, c in enumerate(IS_ORDER)}

def is_key(s):
    out = []
    for ch in s.lower():
        if ch in RANK: out.append((0, RANK[ch]))
        elif ch.isdigit(): out.append((-1, int(ch)))
        else:
            base = unicodedata.normalize('NFD', ch)[0]
            out.append((0, RANK[base]) if base in RANK else (1, ord(ch)))
    return out

def webp(src, dst, longest, q):
    with Image.open(src) as im:
        im = im.convert('RGB')
        w, h = im.size
        if max(w, h) > longest:
            s = longest / max(w, h)
            im = im.resize((round(w * s), round(h * s)), Image.LANCZOS)
        im.save(dst, 'WEBP', quality=q, method=6)
        return im.size

def main():
    for d in (OUT_ROLL, OUT_SHOP):
        shutil.rmtree(d, ignore_errors=True); os.makedirs(d, exist_ok=True)

    pool = json.load(open(os.path.join(ROOT, 'research/pool.json')))
    rows = []
    for r in pool:
        f = r.get('file')
        if not f or not os.path.exists(f):
            continue
        try:
            with Image.open(f) as im:
                r['w'], r['h'] = im.size
        except Exception:
            continue
        rows.append(r)

    # The roll takes pool.json IN ORDER, because tools/fetch.py already put the canon
    # first for a reason (see the CANON note there). Re-sorting by resolution here is
    # exactly the bug that produced a Bad Taste roll with no Björk and an Elvis record:
    # the classical archive simply has bigger scans. Resolution is a FLOOR, not the rank.
    roll_pool = [r for r in rows if min(r['w'], r['h']) >= 1000]
    roll = sorted(roll_pool[:ROLL_COUNT], key=lambda r: is_key(r['artist']))
    for r in roll:
        # 1440, not the 3362 some sources offer: a full-bleed plate covers at most a 1440
        # viewport here, and an oversized WebP is a long-task decode mid-roll.
        r['ow'], r['oh'] = webp(r['file'], os.path.join(OUT_ROLL, r['slug'] + '.webp'), 1440, 80)
        # A 40px WASH for the archive tier's backdrop, so a blurred second copy of a
        # full-size image never has to be decoded (that was 7fps on the 12 Tónar build).
        webp(r['file'], os.path.join(OUT_ROLL, r['slug'] + '-w.webp'), 40, 60)
        # The phone plate. 390px at dpr3 wants ~1170, not 1440.
        r['mw'], r['mh'] = webp(r['file'], os.path.join(OUT_ROLL, r['slug'] + '-m.webp'), 760, 78)

    # the rail: real stock, real ISK price, real link. Skip anything priced 0 (those are
    # variable products whose base price the Store API reports as empty).
    shop_pool = [r for r in rows if r['price'] > 0]
    shop_pool.sort(key=lambda r: -min(r['w'], r['h']))
    shop = sorted(shop_pool[:SHOP_COUNT], key=lambda r: is_key(r['artist']))
    for r in shop:
        r['sw'], r['sh'] = webp(r['file'], os.path.join(OUT_SHOP, r['slug'] + '.webp'), SHOP_MAX, 82)

    def js(v):
        return json.dumps(v, ensure_ascii=False)

    lines = ['''/* Generated by tools/assets.py from Smekkleysa's own WooCommerce catalogue,
   harvested 2026-08-12 through their open Store API. Name, title, price and file are
   emitted from the SAME record, so a caption can never drift onto the wrong sleeve.
   Do not hand-edit.

   w/h are the emitted asset's true pixels; nothing is ever rendered larger.
   `full` marks the sleeves big enough to cover a 1440 viewport honestly. */
export const ARTISTS = [''']
    for r in roll:
        full = min(r['ow'], r['oh']) >= FULLBLEED
        lines.append(
            f"  {{ name: {js(r['artist'])}, slug: {js(r['slug'])}, "
            f"w: {r['ow']}, h: {r['oh']}, mw: {r['mw']}, title: {js(r['title'])}, "
            f"fmt: \"LP\", price: {r['price']}{', full: true' if full else ''} }},")
    lines.append('];\n')
    lines.append('''/* The rail: real stock in their own shop, with the real ISK price and a link to the
   real product page. Prices read 2026-08-12. */
export const RELEASES = [''')
    for r in shop:
        lines.append(
            f"  {{ artist: {js(r['artist'])}, title: {js(r['title'])}, "
            f"format: \"LP\", price: {r['price']}, slug: {js(r['slug'])}, "
            f"w: {r['sw']}, h: {r['sh']}, url: {js(r['url'])} }},")
    lines.append('];')

    with open(os.path.join(ROOT, 'src/roster.mjs'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    full_n = sum(1 for r in roll if min(r['ow'], r['oh']) >= FULLBLEED)
    # compare like with like: emitted WIDTH against source WIDTH.
    up = max(max(r['ow'] / r['w'] for r in roll), max(r['sw'] / r['w'] for r in shop))
    print(f'roll {len(roll)} artists ({full_n} full-bleed, {len(roll) - full_n} archive plates)')
    print(f'rail {len(shop)} releases')
    print(f'max emitted/source ratio {up:.3f} (must be <= 1.0)')

main()
